# Generated by Django 5.0 on 2024-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vrified',
            field=models.BooleanField(default=False),
        ),
    ]
