# Generated by Django 5.0 on 2024-03-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_is_vrified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_vrified',
            new_name='is_verified',
        ),
    ]
